In [135]:
import numpy as np

In [136]:
arr = np.random.rand(10)*100
print(arr)
print(np.sqrt(arr, arr))
remainder, whole_part = np.modf(arr)
print(whole_part)

[82.62056958 80.07696871 62.9777923  21.6324023  51.82603667 59.72740724
 52.50315009 26.0233368  51.52479243 49.11863409]
[9.08958578 8.94857356 7.93585486 4.65106464 7.19903026 7.72835087
 7.24590575 5.10130736 7.17807721 7.00846874]
[9. 8. 7. 4. 7. 7. 7. 5. 7. 7.]


In [137]:
balance = np.array([1000,300,1200,400,180,650,70,4560])
balance = np.where(balance<500 , 0,balance)
print(balance)

[1000    0 1200    0    0  650    0 4560]


In [138]:
values = np.arange(20).reshape((5,4))
print(values)
print(values.cumsum(axis = 0))
prod = values.cumprod(axis = 1)
print(prod)
print(values.min())
print(values.max())
print((prod>1000).sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]]
[[    0     0     0     0]
 [    4    20   120   840]
 [    8    72   720  7920]
 [   12   156  2184 32760]
 [   16   272  4896 93024]]
0
19
5


In [139]:
arr2 = np.random.rand(12).reshape(4,3)*100
print(arr2)
arr2.sort(0)
print(arr2)
np.save('saved_arr',arr2)

[[99.63357758 89.7436148  46.33807482]
 [62.29373829 74.78716041  3.48651602]
 [89.49214412 86.01268164 45.74320978]
 [39.11697661 27.29593749 47.66768283]]
[[39.11697661 27.29593749  3.48651602]
 [62.29373829 74.78716041 45.74320978]
 [89.49214412 86.01268164 46.33807482]
 [99.63357758 89.7436148  47.66768283]]


In [140]:
saved_arr = np.load('saved_arr.npy')
print(saved_arr.T.dot(saved_arr))

[[23346.34133075 22365.44305625 11882.09295025]
 [22365.44305625 21790.28536671 11779.70473499]
 [11882.09295025 11779.70473499  6524.02219956]]


In [141]:
arr3 = np.random.rand(12)*10
arr3 = arr3.astype(int)
arr4 = np.unique(arr3)
print(arr4)
print(arr3)
even = np.in1d(arr4,[0,2,4,6,8])
even.all()



[0 2 3 5 6 7 8 9]
[0 8 0 3 9 7 2 2 0 6 0 5]


False