In [157]:
import numpy as np

In [158]:
# ex1
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b

print(c)

[[11 13 15]
 [17 19 21]]


In [160]:
# ex2
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

[[2 3 1]
 [4 2 1]]


In [161]:
# ex3
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')

print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


In [162]:
# ex4
o = np.full((2, 3), 5)
print(o)

[[5 5 5]
 [5 5 5]]


In [163]:
# ex5
np.random.seed(42)
M = np.random.randint(10, size=(2,2,10))
print(M)

[[[6 3 7 4 6 9 2 6 7 4]
  [3 7 7 2 5 4 1 7 5 1]]

 [[4 0 9 5 8 0 9 2 6 3]
  [8 2 4 2 6 4 8 6 1 3]]]


In [164]:
s = M[:,:,9]
print(s)

[[4 1]
 [3 3]]


In [165]:
s = M[0,1,::2]
print(s)

[3 7 5 1 5]


In [166]:
s = M[:,:,1::2]
print(s)

[[[3 4 9 6 4]
  [7 2 4 7 1]]

 [[0 5 0 2 3]
  [2 2 4 6 3]]]
