In [39]:
import numpy as np

In [40]:
names = np.array(['ahmed', 'mohammed', 'anas', 'foad', 'loay', 'gamal', 'saed'])
ids = np.array(['120215568', '120216874', '120219874', '120214532', '120212258', '120214521', '120217452'])
grades = np.array([[94,85,88], [75,89,91], [92,84,82], [74,78,81], [72,73,77], [64,82,78], [95,92,89]])
GPAs = np.array([89, 85, 86, 77, 74, 74, 92])

mask = GPAs >= 85
print(mask)

print(names[mask],ids[mask],grades[mask])

grades[GPAs > 90, 2] = 90

grades[grades >= 90] = 100


[ True  True  True False False False  True]
['ahmed' 'mohammed' 'anas' 'saed'] ['120215568' '120216874' '120219874' '120217452'] [[94 85 88]
 [75 89 91]
 [92 84 82]
 [95 92 89]]


In [41]:
arr = np.arange(16).reshape((4, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [42]:
arr[[0,1,2,2,3],[0,1,1,2,0]]

array([ 0,  5,  9, 10, 12])

In [43]:
arr = np.arange(30).reshape((2, 3, 5))
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [44]:
arr.transpose((2,1,0))

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])