In [2]:
import numpy as np

In [34]:
arr = np.arange(15)
arr2 = arr.reshape((5, 3),order='F')
print(arr2)
arr2.ravel('c')

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [46]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr =np.vstack((arr1, arr2))
print(arr)
first, second, third = np.split(arr, [2, 3])
print("first:",first)
print("second:",second)
print("third:",third)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
first: [[1 2 3]
 [4 5 6]]
second: [[7 8 9]]
third: [[10 11 12]]


In [64]:
arr = np.random.randn(3,3)
print(arr)
print("\n")
repeated = arr.repeat([2, 3, 4], axis= 0)
print(repeated)
tiled = np.tile(arr, (3, 2))
print("\n")
print(tiled.shape)

[[ 1.89080805 -1.23583153 -0.57088649]
 [ 1.60120439 -0.02710394  1.1972199 ]
 [ 0.47423127 -1.46636807 -0.74641497]]


[[ 1.89080805 -1.23583153 -0.57088649]
 [ 1.89080805 -1.23583153 -0.57088649]
 [ 1.60120439 -0.02710394  1.1972199 ]
 [ 1.60120439 -0.02710394  1.1972199 ]
 [ 1.60120439 -0.02710394  1.1972199 ]
 [ 0.47423127 -1.46636807 -0.74641497]
 [ 0.47423127 -1.46636807 -0.74641497]
 [ 0.47423127 -1.46636807 -0.74641497]
 [ 0.47423127 -1.46636807 -0.74641497]]


(9, 6)


In [3]:
r = lambda a : a + 15
print(r(10))
r = lambda x, y : x * y
print(r(12, 4))

25
48


In [4]:
def func_compute(n):
 return lambda x : x * n
result = func_compute(2)
print("Double the number of 15 =", result(15))
result = func_compute(3)
print("Triple the number of 15 =", result(15))
result = func_compute(4)
print("Quadruple the number of 15 =", result(15))
result = func_compute(5)
print("Quintuple the number 15 =", result(15))

Double the number of 15 = 30
Triple the number of 15 = 45
Quadruple the number of 15 = 60
Quintuple the number 15 = 75


In [ ]:
# Q6) Write a Python program to sort a list of tuples using Lambda. 
# Original list of tuples:
# [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
# Sorting the List of Tuples:
# [('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [65]:
# subject_marks = [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
# print("Original list of tuples:")
# print(subject_marks)
# subject_marks.sort(key = lambda x: x[1])
# print("\nSorting the List of Tuples:")
# print(subject_marks)