In [2]:
import numpy as np
import re

In [4]:
# Q1
x = "AliAhmed8922@hotmail.com \nNihal.Nael@outlook.com \nmohammed2022fa@gmail.com"
y = re.findall('.*@([^.]*)', x)
x,y

('AliAhmed8922@hotmail.com \nNihal.Nael@outlook.com \nmohammed2022fa@gmail.com',
 ['hotmail', 'outlook', 'gmail'])

In [7]:
#Q2
def text_match(text):
        patterns = '^[a-zA-Z0-9_]*$'
        if re.search(patterns,  text):
                return 'Found a match!'
        else:
                return('Not matched!')

print(text_match("The beautiful lady came to the party yesterday"))
print(text_match("Symon says_ jump"))
print(text_match("Midterm_Exam_24"))


Not matched!
Not matched!
Found a match!


In [8]:
# Q3
names = np.array(['sanaa', 'mohammed', 'hani', 'farah', 'esam', 'manal', 'inas'])
grades = np.array([[70,85,74], [40,53,48], [93,89,94], [92,84,82], [42,46,51], [72,73,77], [95,92,89]])
results = np.array(['passed', 'failed', 'passed', 'passed', 'failed', 'passed', 'passed'])

mask = results == 'passed'
print(mask)

print(names[mask])
print(grades[mask])
mask2 = results =='failed'
GPAs_failed = grades[mask2,:].sum(axis = 1)/3
print(50-GPAs_failed)



[ True False  True  True False  True  True]
['sanaa' 'hani' 'farah' 'manal' 'inas']
[[70 85 74]
 [93 89 94]
 [92 84 82]
 [72 73 77]
 [95 92 89]]
[3.         3.66666667]


In [9]:
# Q4
values = np.arange(20).reshape((5,4))
print(values)
summ = values.cumsum()
meann = summ.mean()
print(meann)
np.savez('array_archive.npz', a=summ, b=meann)
savedd = np.load('array_archive.npz')
savedd['b']

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
66.5


array(66.5)

In [11]:
# Q5
arr = np.random.rand(10)*100
print(arr)
remainder, whole_part = np.modf(arr)
arr = np.where(whole_part>=50 , "success","fail")
print(arr)
fail = np.in1d(arr,"fail")
print(fail)
fail.any()

[61.49822002 52.16955039  8.75372272 99.87111344 78.95903372 88.46520031
 45.42720443 43.02800139 62.60412221 69.2924935 ]
['success' 'success' 'fail' 'success' 'success' 'success' 'fail' 'fail'
 'success' 'success']
[False False  True False False False  True  True False False]


True

In [12]:
# Q6
arr = np.arange(16).reshape((4, 4))
print(arr)
print(arr[[0,0,1,1,2,2,3,3,3],[1,2,0,3,0,2,0,2,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  2  4  7  8 10 12 14 15]


In [13]:
# Q7
arr = np.arange(15).reshape((5,3))
arr.flatten('F')
arr3 = arr.reshape((5, 3),order='C')

first, second, third,fourth = np.split(arr, [1,2,4])
print("first:",first)
print("second:",second)
print("third:",third)
print("fourth:",fourth)
repeated = third.repeat([2, 3, 5], axis= 1)
print(repeated)

first: [[0 1 2]]
second: [[3 4 5]]
third: [[ 6  7  8]
 [ 9 10 11]]
fourth: [[12 13 14]]
[[ 6  6  7  7  7  8  8  8  8  8]
 [ 9  9 10 10 10 11 11 11 11 11]]
